apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: spa-client
spec:
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spa-client