controller:
  replicaCount: 2
  nodeSelector:
    "beta.kubernetes.io/os": "linux"
  admissionWebhooks:
    patch:
      nodeSelector:
        "beta.kubernetes.io/os": "linux"
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: $RESOURCE_GROUP
    loadBalancerIP: "$INGRESS_IP"
  extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aks-tls"
  extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true
defaultBackend:
  nodeSelector:
    "beta.kubernetes.io/os": "linux"
