# This is a SecretProviderClass example using a service principal to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aks-tls
spec:
  provider: azure
  secretObjects:
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data:
    - objectName: ingress-tls
      key: tls.key
    - objectName: ingress-tls
      key: tls.crt
  parameters:
    keyvaultName: "pgdemo-keyvault" # the name of the KeyVault
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "$MANAGED_ID"
    objects:  |
      array:
        - |
          objectName: ingress-tls
          objectType: secret
    tenantId: "$TENANT_ID"