apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgdemo-basic
  labels:
    app: pgdemo-basic
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: pgdemo-basic
  template:
    metadata:
      labels:
        app: pgdemo-basic
    spec:
      containers:
      - name: pgdemo-basic
        image: pgdemoacr.azurecr.io/pgdemo:0.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m       # 0.1 of a cpu
            memory: 128Mi   # minimum size for running
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /shared/java-agent
          name: java-agent
        env:
        - name: JAVA_OPTIONS
          value: -javaagent:/shared/java-agent/applicationinsights-agent.jar
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: pgdemo-basic-secret
              key: instrumentationKey
      initContainers:
      - name: init-agent
        image: pgdemoacr.azurecr.io/applicationinsights-agent:latest
        command: ["cp", "applicationinsights-agent.jar", "/shared/java-agent"]
        volumeMounts:
        - mountPath: /shared/java-agent
          name: java-agent
      volumes:
      - name: java-agent
        emptyDir: {}