apiVersion: v1
kind: Service
metadata:
  name: pgdemo-basic-ingrss
spec:
  type: ExternalName
  externalName: pgdemo-basic.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: bff-ingress
spec:
  type: ExternalName
  externalName: bff.default.svc.cluster.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgdemo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: ingress-tls-csi
    hosts:
    - ${DEMO_DOMAIN_NAME}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: pgdemo-basic
            port:
              number: 8080
        path: /basic
        pathType: Prefix
      - backend:
          service:
            name: bff
            port:
              number: 8090
        path: /bff
        pathType: Prefix
