apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: bff
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bff
