apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  backoffLimit: 0
  template:
    metadata:
      name: db-migrate
    spec:
      restartPolicy: Never
      containers:
      - name:  db-migrate
        image: pgdemoacr.azurecr.io/db-migrate:0.1.0
        imagePullPolicy: Always
        env:
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: pgdemo-basic-secret
              key: postgresUser
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgdemo-basic-secret
              key: postgresPassword
        - name: POSTGRESQL_HOST
          valueFrom:
            secretKeyRef:
              name: pgdemo-basic-secret
              key: postgresHost
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: pgdemo-basic-secret
              key: postgresDatabase
