version: '3'
services:
  db:
    image: postgres:11-alpine
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: adminuserpasswd
  redis:
    image: "redis:4.0.14-alpine"
    ports:
      - "6379:6379"